name: $mpds_visavis

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'visavis'
        modules: 'app'

    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      if: github.ref == 'refs/heads/master'
      with:
        site-directory: 'visavis/app/-'
